repos:

- repo: local
  hooks:
  - id: pip-compile
    name: compile requirements.txt
    entry: pip-compile --index_url https://artifactory.k8s.devops.s-9.us/artifactory/api/pypi/pypi/simple
    language: system
    always_run: false
    files: setup.py
    stages: [push]
    pass_filenames: false